/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jsubmodule;

public class Library {
    public void print(final String stringToPrint) {
        System.out.println(stringToPrint);
    }

    public String numberToString(final int number) {
        return String.valueOf(number);
    }

    public int stringToNumber(final String number) {
        try {
            return Integer.parseInt(number);
        }
        catch(Exception e) {
            e.printStackTrace();
        }

        return 0;
    }
}
