/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jsubmodule;

public class Library {
    public void print(final String stringToPrint) {
        System.out.println(stringToPrint);
    }

    public String numberToString(final int number) {
        return String.valueOf(number);
    }
}
